---
networks:
  backend:
    name: backend

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-17.7-alpine}
    restart: always
    environment:
      - PGDATA=${PGDATA:-/var/lib/postgresql/17/docker}
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - backend
    volumes:
      - ${POSTGRES_LOCAL_DATA_DIR:-/var/lib/postgresql/data}:${POSTGRES_DATA_DIR:-/var/lib/postgresql/data}
    ports:
      - ${POSTGRES_EXPOSED_PORT}:5432
    healthcheck:
      test: pg_isready -U $${POSTGRES_USER} -h localhost -d $${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 105

  migrator:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: app
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - ConnectionStrings__DefaultConnection=Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
  #     - ASPNETCORE_URLS=http://+:8080
  #   networks:
  #     - backend
  #   depends_on:
  #     migrator:
  #       condition: service_completed_successfully
